version: "3.8"
services:
  app:
    container_name: app
    build:
      args:
        user: www-data
        uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./api:/usr/src/app
      - ./api/public:/usr/src/app/public
    depends_on:
      - mysql
    networks:
      - app_network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./api/public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - app
    environment:
      NGINX_FPM_HOST: app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./api/storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: libraries
      MYSQL_ROOT_PASSWORD: libraries
      MYSQL_USER: root
      MYSQL_PASSWORD: libraries
    networks:
      - app_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge